# Emotion Detection from Text
## Problem Statement
The objective of this project is to classify human emotions from textual data into categories such as joy, sadness, anger, fear, etc.

This helps in:
- Sentiment analysis
- Customer feedback analysis
- Social media monitoring

## Import Required Libraries

Libraries used:
- Pandas, NumPy → data handling
- Matplotlib, Seaborn → visualization
- Scikit-learn → ML models & evaluation
- NLP tools → text preprocessing

In [2]:
## Import of basic libraray
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('train.txt',sep=';',header=None,names=['text','emotion'])

In [4]:
df

                                                    text  emotion
0                                i didnt feel humiliated  sadness
1      i can go from feeling so hopeless to so damned...  sadness
2       im grabbing a minute to post i feel greedy wrong    anger
3      i am ever feeling nostalgic about the fireplac...     love
4                                   i am feeling grouchy    anger
...                                                  ...      ...
16155                               this feels pointless   boring
16156                           i feel drained and bored   boring
16157                              this is uninteresting   boring
16158                                    i am zoning out   boring
16159                                  this is very dull   boring

[16160 rows x 2 columns]

In [5]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [6]:
## Converting the emotion columns to numbers 

unique_emotions=df['emotion'].unique()
emotion_numbers={}
i=0

for  emo in unique_emotions:
    emotion_numbers[emo]=i
    i=+1
    
    
df['emotion']=df['emotion'].map(emotion_numbers)

In [7]:
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        1
4                                   i am feeling grouchy        1
...                                                  ...      ...
16155                               this feels pointless        1
16156                           i feel drained and bored        1
16157                              this is uninteresting        1
16158                                    i am zoning out        1
16159                                  this is very dull        1

[16160 rows x 2 columns]

In [8]:
## Converting the text columns to Lower   I--=>i 
df['text']=df['text'].apply(lambda x : x.lower())

In [9]:
## removing the Puntuation from the columns   I--=>i 

import string
def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

#OR

####df['text'] = df['text'].apply(lambda x: x.translate(str.maketrans('', '', string.punctuation)))

In [12]:
df['text'] = df['text'].apply(remove_punc)

In [13]:
## removing the Number  from the columns   
def remove_numbers(txt):
    new=""
    for i in txt:
        if not i.isdigit():
            new=new+i
            
    return new

df['text']=df['text'].apply(remove_numbers)

In [14]:

## removing the emojis from the columns   

def remove_emojis(txt):
    new=""
    for i in txt:
        if i.isascii():
            new +=i
            
    return new




df['text']=df['text'].apply(remove_emojis)

## Text Preprocessing

Steps performed:
- Lowercasing text
- Removing punctuation & special characters
- Stopword removal
- Tokenization

Goal:
Convert raw text into clean format for modeling

In [17]:
import nltk

In [18]:
from nltk.corpus import stopwords
from  nltk.tokenize import word_tokenize


## removing the stopwords from the columns   so we download the libraraies

In [19]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\jigar\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jigar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [20]:
stopwords=set(stopwords.words('english'))

In [22]:
## removing the stopwords from the columns 
def remove(txt):
    words=txt.split()
    cleaned=[]
    for i in words:
        if not i in stopwords:
            cleaned.append(i)
            
            
            
    return ''.join(cleaned)
    
##                        OR


# def clean_text(txt):
#     words = txt.split()
#     return ' '.join([w for w in words if w not in stop_words])

In [24]:
df['text']=df['text'].apply(remove)

In [25]:
df.loc[1]['text']

'gofeelinghopelessdamnedhopefularoundsomeonecaresawake'

##  Train-Test Split

- Split data into training and testing sets
- Ensures unbiased evaluation

In [26]:
## training the model
from sklearn.model_selection import train_test_split

In [27]:
 X_train, X_test, y_train, y_test = train_test_split(
...     df['text'],df['emotion'], test_size=0.20, random_state=42)

In [28]:
X_train

13352    beginwritebackgodexpressingthoughtsfeelingsfea...
9219                                       feelplacetragic
744                               startedfeelkindskeptical
1965     feelcompletelyhelplessanythinghelpaffectedtorn...
6350     couldfeeltearswellingeyesfeltdisappointedlackf...
                               ...
13418       loveleavereaderfeelingconfusedslightlydeceived
5390                                          feeldelicate
860                             startingfeellittlestressed
15795                  feelstressedtiredwornshapeneglected
7270               feelsomeonerudewronglydonesomethinglose
Name: text, Length: 12928, dtype: object

## Training the model using TFIDF for converts text → numbers so a model can learn


## Feature Engineering (TF-IDF)

We convert text into numerical vectors using:
- TF-IDF Vectorization

This helps models understand importance of words

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [ ]:
##CountVectorizer is the simpler version you should compare it against—not memorize blindly.
bow_vector=CountVectorizer()

In [ ]:
X_train_bow=bow_vector.fit_transform(X_train)
X_test_bow=bow_vector.fit_transform(X_test)

In [ ]:
X_test_bow

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)


nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)


pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))

In [ ]:

tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)


nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)
y_pred = nb2_model.predict(X_test_tfidf)
print(accuracy_score(y_test, y_pred))

In [ ]:
from sklearn.linear_model import LogisticRegression
logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train_tfidf,y_train)
log_pred = logistic_model.predict(X_test_tfidf)
print(accuracy_score(y_test,log_pred ))

#                   All in one for Deployment

In [1]:
import pandas as pd
import string
import nltk
import joblib

from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score, classification_report

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV   # ✅ added

nltk.download('stopwords')

# =========================
# 1. LOAD DATA
# =========================
df = pd.read_csv('train.txt', sep=';', header=None, names=['text', 'emotion'])

# =========================
# 2. LABEL ENCODING
# =========================
df['emotion'] = df['emotion'].astype('category')
label_map = dict(enumerate(df['emotion'].cat.categories))
df['label'] = df['emotion'].cat.codes

# =========================
# 3. TEXT PREPROCESSING
# =========================
df['text'] = df['text'].str.lower()
df['text'] = df['text'].apply(lambda x: x.translate(str.maketrans('', '', string.punctuation)))
df['text'] = df['text'].str.replace(r'\d+', '', regex=True)
df['text'] = df['text'].apply(lambda x: ''.join([i for i in x if i.isascii()]))

stop_words = set(stopwords.words('english'))

def clean_text(txt):
    words = txt.split()
    return ' '.join([w for w in words if w not in stop_words])

df['text'] = df['text'].apply(clean_text)

# =========================
# 4. TRAIN TEST SPLIT
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    df['text'], df['label'], test_size=0.2, random_state=42
)

# =========================
# 5. TF-IDF
# =========================
vectorizer = TfidfVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# =========================
# 6. MODELS (UPDATED)
# =========================
models = {
    "Naive Bayes": MultinomialNB(),
    "Logistic Regression": LogisticRegression(max_iter=200),
    "Random Forest": RandomForestClassifier(n_estimators=100),
    
    # ✅ FIX: SVM with probability support
    "Linear SVM": CalibratedClassifierCV(LinearSVC())
}

results = {}

for name, model in models.items():
    model.fit(X_train_vec, y_train)
    preds = model.predict(X_test_vec)
    acc = accuracy_score(y_test, preds)
    
    results[name] = acc
    
    print(f"\n{name} Accuracy: {acc:.4f}")
    print(f"{name} Report:")
    print(classification_report(y_test, preds))

# =========================
# 7. SELECT BEST MODEL
# =========================
best_model_name = max(results, key=results.get)
best_model = models[best_model_name]

print("\nBest Model:", best_model_name)
print("Best Accuracy:", results[best_model_name])

# =========================
# 8. SAVE
# =========================
joblib.dump(best_model, "model.pkl")
joblib.dump(vectorizer, "vectorizer.pkl")
joblib.dump(label_map, "labels.pkl")

print("Label Mapping:", label_map)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\jigar\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

Naive Bayes Accuracy: 0.6584
Naive Bayes Report:
              precision    recall  f1-score   support

           0       0.96      0.31      0.46       424
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00         5
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         6
           5       0.85      0.20      0.32       383
           6       0.00      0.00      0.00         7
           7       0.60      0.98      0.74      1050
           8       1.00      0.04      0.08       280
           9       0.00      0.00      0.00         6
          10       0.69      0.93      0.79       944
          11       0.00      0.00      0.00         3
          12       1.00      0.01      0.02       118
          13       0.00      0.00      0.00         3

    accuracy                           0.66      3232
   macro avg       0.36      0.18      0.17      3232
weighted avg       0.75      0.66      0.58      3232

C:\Users\jigar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jigar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jigar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Logistic Regression Accuracy: 0.8478
Logistic Regression Report:
              precision    recall  f1-score   support

           0       0.92      0.79      0.85       424
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00         5
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         6
           5       0.84      0.74      0.79       383
           6       0.00      0.00      0.00         7
           7       0.80      0.96      0.87      1050
           8       0.89      0.59      0.71       280
           9       0.00      0.00      0.00         6
          10       0.88      0.93      0.90       944
          11       0.00      0.00      0.00         3
          12       0.86      0.52      0.65       118
          13       0.00      0.00      0.00         3

    accuracy                           0.85      3232
   macro avg       0.37      0.32      0.34      3232
weighted avg       0.84      0.85      0.84      3232

C:\Users\jigar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jigar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jigar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Random Forest Accuracy: 0.8694
Random Forest Report:
              precision    recall  f1-score   support

           0       0.87      0.85      0.86       424
           1       0.00      0.00      0.00         2
           2       1.00      0.20      0.33         5
           3       0.00      0.00      0.00         1
           4       1.00      0.17      0.29         6
           5       0.83      0.86      0.84       383
           6       0.00      0.00      0.00         7
           7       0.86      0.92      0.89      1050
           8       0.82      0.71      0.76       280
           9       0.33      0.17      0.22         6
          10       0.93      0.91      0.92       944
          11       0.00      0.00      0.00         3
          12       0.83      0.74      0.78       118
          13       0.33      0.33      0.33         3

    accuracy                           0.87      3232
   macro avg       0.56      0.42      0.45      3232
weighted avg       0.87      0.87      0.87      3232

C:\Users\jigar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jigar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jigar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jigar\anaconda3\lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\jigar\anaconda3\lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\jigar\anaconda3\lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\jigar\anaconda3\lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\jigar\anaconda3\lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(

Linear SVM Accuracy: 0.8800
Linear SVM Report:
              precision    recall  f1-score   support

           0       0.89      0.86      0.88       424
           1       0.00      0.00      0.00         2
           2       0.00      0.00      0.00         5
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         6
           5       0.84      0.84      0.84       383
           6       0.00      0.00      0.00         7
           7       0.88      0.94      0.91      1050
           8       0.83      0.74      0.78       280
           9       1.00      0.17      0.29         6
          10       0.91      0.93      0.92       944
          11       0.00      0.00      0.00         3
          12       0.82      0.75      0.78       118
          13       1.00      0.33      0.50         3

    accuracy                           0.88      3232
   macro avg       0.51      0.40      0.42      3232
weighted avg       0.87      0.88      0.88      3232


Best Model: Linear SVM
Best Accuracy: 0.879950495049505

C:\Users\jigar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jigar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\jigar\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Label Mapping: {0: 'anger', 1: 'anticipation', 2: 'boring', 3: 'confusion', 4: 'disgust', 5: 'fear', 6: 'guilt', 7: 'joy', 8: 'love', 9: 'pride', 10: 'sadness', 11: 'shame', 12: 'surprise', 13: 'trust'}

##  Conclusion

- Successfully built an emotion classification model
- Used NLP + ML techniques for prediction
- Improved performance using tuning and ensemble learning

###  Key Takeaways
- Text preprocessing is critical in NLP
- TF-IDF is effective for baseline models
- Pipelines improve workflow efficiency